@echo off
echo Starting Backend...
start cmd /k "cd Backend && .\venv\Scripts\uvicorn main:app --reload --port 8000"
echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
echo F1 Dashboard is starting!
